export const RABBIT_HOLE_SBT_ABI = [
  {
    type: "constructor",
    inputs: [
      { name: "collectionName", type: "string" },
      { name: "collectionSymbol", type: "string" },
      { name: "initialOwner", type: "address" },
      { name: "initialMinter", type: "address" },
    ],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "mint",
    stateMutability: "nonpayable",
    inputs: [
      { name: "recipient", type: "address" },
      { name: "uri", type: "string" },
      { name: "claimKey", type: "bytes32" },
    ],
    outputs: [{ name: "tokenId", type: "uint256" }],
  },
  {
    type: "function",
    name: "tokenOfClaim",
    stateMutability: "view",
    inputs: [{ name: "claimKey", type: "bytes32" }],
    outputs: [{ name: "tokenId", type: "uint256" }],
  },
  {
    type: "function",
    name: "tokenOfOwner",
    stateMutability: "view",
    inputs: [{ name: "account", type: "address" }],
    outputs: [{ name: "tokenId", type: "uint256" }],
  },
  {
    type: "function",
    name: "ownerOf",
    stateMutability: "view",
    inputs: [{ name: "tokenId", type: "uint256" }],
    outputs: [{ name: "tokenOwner", type: "address" }],
  },
  {
    type: "function",
    name: "locked",
    stateMutability: "view",
    inputs: [{ name: "tokenId", type: "uint256" }],
    outputs: [{ name: "", type: "bool" }],
  },
  {
    type: "function",
    name: "minter",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "", type: "address" }],
  },
  {
    type: "function",
    name: "approve",
    stateMutability: "pure",
    inputs: [{ name: "", type: "address" }, { name: "", type: "uint256" }],
    outputs: [],
  },
  {
    type: "function",
    name: "setApprovalForAll",
    stateMutability: "pure",
    inputs: [{ name: "", type: "address" }, { name: "", type: "bool" }],
    outputs: [],
  },
  {
    type: "function",
    name: "transferFrom",
    stateMutability: "pure",
    inputs: [
      { name: "", type: "address" },
      { name: "", type: "address" },
      { name: "", type: "uint256" },
    ],
    outputs: [],
  },
  {
    type: "function",
    name: "safeTransferFrom",
    stateMutability: "pure",
    inputs: [
      { name: "", type: "address" },
      { name: "", type: "address" },
      { name: "", type: "uint256" },
    ],
    outputs: [],
  },
  {
    type: "function",
    name: "safeTransferFrom",
    stateMutability: "pure",
    inputs: [
      { name: "", type: "address" },
      { name: "", type: "address" },
      { name: "", type: "uint256" },
      { name: "", type: "bytes" },
    ],
    outputs: [],
  },
  {
    type: "event",
    name: "SoulboundMinted",
    anonymous: false,
    inputs: [
      { name: "recipient", type: "address", indexed: true },
      { name: "tokenId", type: "uint256", indexed: true },
      { name: "claimKey", type: "bytes32", indexed: true },
      { name: "tokenUri", type: "string", indexed: false },
    ],
  },
  {
    type: "event",
    name: "Locked",
    anonymous: false,
    inputs: [{ name: "tokenId", type: "uint256", indexed: false }],
  },
] as const;
